// content/vocab/en10.u5.ts
import type { UnitVocab } from "../english10.vocab";

/**
 * Unit 5 vocabulary – Inventions
 */

const data: UnitVocab = {
  unitId: 5,
  unitTitle: "Unit 5: Inventions",
  lessons: [
    {
      key: "vocabulary-1",
      title: "Từ vựng Unit 5 – Phần 1",
      baseImagePath: "/images/vocab/u5/",
      items: [
        {
          id: "3d-printing",
          word: "3D printing",
          ipa: "/θriː diː ˈprɪntɪŋ/",
          pos: "n. phr.",
          vi: "in 3D, in 3 chiều",
          exampleEn: "It’s not easy to use 3-D printing.",
          exampleVi: "Không dễ để sử dụng công nghệ in 3D.",
          imageFile: "3d-printing.jpg",
        },
        {
          id: "ai-artificial-intelligence",
          word: "AI (artificial intelligence)",
          ipa: "/ˌeɪ ˈaɪ/ (/ˌɑːtɪfɪʃl ɪnˈtelɪdʒəns/)",
          pos: "n.",
          vi: "trí tuệ nhân tạo",
          exampleEn: "Nowadays, people use AI in various areas of life.",
          exampleVi: "Ngày nay, con người sử dụng trí tuệ nhân tạo trong nhiều lĩnh vực khác nhau của cuộc sống.",
          imageFile: "ai-artificial-intelligence.jpg",
        },
        {
          id: "app-application",
          word: "app (application)",
          ipa: "/æp/ (/ˌæplɪˈkeɪʃn/)",
          pos: "n.",
          vi: "ứng dụng (trên điện thoại)",
          exampleEn: "Have you got the facebook app on your phone?",
          exampleVi: "Bạn đã có ứng dụng facebook trên điện thoại của mình chưa?",
          imageFile: "app-application.jpg",
        },
        {
          id: "apply",
          word: "apply",
          ipa: "/əˈplaɪ/",
          pos: "v.",
          vi: "áp dụng",
          exampleEn: "The new technology was applied to farming.",
          exampleVi: "Công nghệ mới đã được áp dụng cho nông nghiệp.",
          imageFile: "apply.jpg",
        },
        {
          id: "bulky",
          word: "bulky",
          ipa: "/ˈbʌlki/",
          pos: "adj.",
          vi: "cồng kềnh",
          exampleEn: "A desktop computer is bulky.",
          exampleVi: "Máy tính để bàn khá cồng kềnh.",
          imageFile: "bulky.jpg",
        },
        {
          id: "button",
          word: "button",
          ipa: "/ˈbʌtn/",
          pos: "n.",
          vi: "nút bấm",
          exampleEn: "She’s pushing the button and waiting for crossing the road.",
          exampleVi: "Cô ấy đang nhấn nút và chờ sang đường.",
          imageFile: "button.jpg",
        },
        {
          id: "charge",
          word: "charge",
          ipa: "/tʃɑːdʒ/",
          pos: "v.",
          vi: "sạc pin",
          exampleEn: "Oh. I need to charge my phone. The battery is very low.",
          exampleVi: "Ồ. Tôi cần sạc điện thoại. Pin rất yếu rồi.",
          imageFile: "charge.jpg",
        },
        {
          id: "collapse",
          word: "collapse",
          ipa: "/kəˈlæps/",
          pos: "v.",
          vi: "sụp đổ, hỏng",
          exampleEn: "My laptop collapsed yesterday when I was working.",
          exampleVi: "Máy tính xách tay của tớ bị hỏng hôm qua lúc tớ đang làm việc.",
          imageFile: "collapse.jpg",
        },
        {
          id: "communicate",
          word: "communicate",
          ipa: "/kəˈmjuːnɪkeɪt/",
          pos: "v.",
          vi: "giao tiếp",
          exampleEn: "We can now communicate instantly with people in different countries in the world.",
          exampleVi: "Giờ đây, chúng tôi có thể giao tiếp tức thì với mọi người ở các quốc gia khác nhau trên thế giới.",
          imageFile: "communicate.jpg",
        },
        {
          id: "correction-pen",
          word: "correction pen",
          ipa: "/kəˈrekʃn pen/",
          pos: "n.",
          vi: "bút xóa",
          exampleEn: "Can I use a correction pen to cover errors?",
          exampleVi: "Em có thể dùng bút xóa để xóa lỗi sai không ạ?",
          imageFile: "correction-pen.jpg",
        },
        {
          id: "device",
          word: "device",
          ipa: "/dɪˈvaɪs/",
          pos: "n.",
          vi: "thiết bị",
          exampleEn: "Our lives have been made easier thanks to modern devices.",
          exampleVi: "Cuộc sống của chúng ta trở nên dễ dàng hơn nhờ có các thiết bị hiện đại.",
          imageFile: "device.jpg",
        },
        {
          id: "digital-camera",
          word: "digital camera",
          ipa: "/ˈdɪdʒɪtl ˈkæmərə/",
          pos: "n. phr.",
          vi: "máy ảnh kĩ thuật số",
          exampleEn: "A digital camera is convenient to use.",
          exampleVi: "Máy ảnh kĩ thuật số rất tiện sử dụng.",
          imageFile: "digital-camera.jpg",
        },
        {
          id: "display",
          word: "display",
          ipa: "/dɪˈspleɪ/",
          pos: "v.",
          vi: "hiển thị, trưng bày",
          exampleEn: "Do you know what the screen is displaying?",
          exampleVi: "Bạn có biết màn hình đang hiển thị gì không?",
          imageFile: "display.jpg",
        },
        {
          id: "drawback",
          word: "drawback",
          ipa: "/ˈdrɔːbæk/",
          pos: "n.",
          vi: "khuyết điểm",
          exampleEn: "Samsung smartphones have certain drawbacks.",
          exampleVi: "Điện thoại thông minh của Samsung có một số khuyết điểm nhất định.",
          imageFile: "drawback.jpg",
        },
        {
          id: "driverless",
          word: "driverless",
          ipa: "/ˈdraɪvələs/",
          pos: "adj.",
          vi: "không người lái",
          exampleEn: "Driverless cars are testing in my country.",
          exampleVi: "Xe ô tô không người lái đang được thử nghiệm ở nước tôi.",
          imageFile: "driverless.jpg",
        },
        {
          id: "earbuds",
          word: "earbuds",
          ipa: "/ˈɪəbʌdz/",
          pos: "n.",
          vi: "tai nghe nhỏ có thể nhét vào tai",
          exampleEn: "You can use earbuds to avoid disturbing others.",
          exampleVi: "Cậu có thể dùng tai nghe để tránh làm phiền người khác.",
          imageFile: "earbuds.jpg",
        },
        {
          id: "e-reader",
          word: "e-reader",
          ipa: "/ˈiː riːdə/",
          pos: "n.",
          vi: "thiết bị đọc sách điện tử",
          exampleEn: "An e-reader can be used to store a lot of e-books.",
          exampleVi: "Thiết bị đọc sách điện tử có thể sử dụng để lưu trữ rất nhiều sách điện tử.",
          imageFile: "e-reader.jpg",
        },
        {
          id: "economical",
          word: "economical",
          ipa: "/ˌekəˈnɒmɪkl/",
          pos: "adj.",
          vi: "tiết kiệm, đáng giá đồng tiền",
          exampleEn: "A pair of earbuds is economical.",
          exampleVi: "Mua một cái tai nghe cũng rẻ thôi.",
          imageFile: "economical.jpg",
        },
        {
          id: "experiment",
          word: "experiment",
          ipa: "/ɪkˈsperɪmənt/",
          pos: "n.",
          vi: "thí nghiệm",
          exampleEn: "Many people do not like the idea of experiments on animals.",
          exampleVi: "Nhiều người không thích ý tưởng thí nghiệm trên động vật.",
          imageFile: "experiment.jpg",
        },
        {
          id: "good-for-nothing",
          word: "good-for-nothing",
          ipa: "/ɡʊd fə ˈnʌθɪŋ/",
          pos: "adj.",
          vi: "vô dụng",
          exampleEn: "That’s not a good-for-nothing invention.",
          exampleVi: "Đó không phải là một phát minh vô dụng.",
          imageFile: "good-for-nothing.jpg",
        },
        {
          id: "headphones",
          word: "headphones",
          ipa: "/ˈhedfəʊnz/",
          pos: "n.",
          vi: "tai nghe (úp vào tai)",
          exampleEn: "Can I borrow your headphones?",
          exampleVi: "Tớ mượn tai nghe của cậu được chứ?",
          imageFile: "headphones.jpg",
        },
        {
          id: "imitate",
          word: "imitate",
          ipa: "/ˈɪmɪteɪt/",
          pos: "v.",
          vi: "bắt chước, sao chép",
          exampleEn: "Some animals can imitate humans’ actions.",
          exampleVi: "Một số loài động vật có thể bắt chước hành động của con người.",
          imageFile: "imitate.jpg",
        },
      ],
    },
    {
      key: "vocabulary-2",
      title: "Từ vựng Unit 5 – Phần 2",
      baseImagePath: "/images/vocab/u5/",
      items: [
        {
          id: "hardware",
          word: "hardware",
          ipa: "/ˈhɑːdweə/",
          pos: "n.",
          vi: "phần cứng",
          exampleEn: "We supply computer hardware to many businesses.",
          exampleVi: "Chúng tôi cung cấp phần cứng máy tính cho rất nhiều doanh nghiệp.",
          imageFile: "hardware.jpg",
        },
        {
          id: "inspiration",
          word: "inspiration",
          ipa: "/ˌɪnspəˈreɪʃn/",
          pos: "n.",
          vi: "cảm hứng",
          exampleEn: "Nature is a source of inspiration for inventors.",
          exampleVi: "Thiên nhiên là nguồn cảm hứng cho các nhà phát minh.",
          imageFile: "inspiration.jpg",
        },
        {
          id: "inspire",
          word: "inspire",
          ipa: "/ɪnˈspaɪə/",
          pos: "v.",
          vi: "truyền cảm hứng",
          exampleEn: "This machine was inspired by a drawing of Leonardo Da Vinci.",
          exampleVi: "Chiếc máy này lấy cảm hứng từ một bức vẽ của Leonardo Da Vinci.",
          imageFile: "inspire.jpg",
        },
        {
          id: "install",
          word: "install",
          ipa: "/ɪnˈstɔːl/",
          pos: "v.",
          vi: "cài (phần mềm, chương trình máy tính)",
          exampleEn: "Do not install programs from websites that you are unfamiliar with.",
          exampleVi: "Đừng cài đặt các chương trình từ các trang web mà bạn không biết.",
          imageFile: "install.jpg",
        },
        {
          id: "invention",
          word: "invention",
          ipa: "/ɪnˈvenʃn/",
          pos: "n.",
          vi: "phát minh",
          exampleEn: "He was given a Nobel prize for his invention.",
          exampleVi: "Anh ấy đã được tặng giải Nobel với phát minh đó.",
          imageFile: "invention.jpg",
        },
        {
          id: "laboratory",
          word: "laboratory",
          ipa: "/ləˈbɒrətəri/",
          pos: "n.",
          vi: "phòng thí nghiệm",
          exampleEn: "Laboratory tests suggest that the new drug may be used to treat cancer.",
          exampleVi: "Các xét nghiệm trong phòng thí nghiệm cho thấy loại thuốc mới này có thể được sử dụng để điều trị ung thư.",
          imageFile: "laboratory.jpg",
        },
        {
          id: "laptop",
          word: "laptop",
          ipa: "/ˈlæptɒp/",
          pos: "n.",
          vi: "máy tính xách tay",
          exampleEn: "A laptop is convenient for studying and entertainment.",
          exampleVi: "Máy tính xách tay tiện lợi cho cả việc học và giải trí.",
          imageFile: "laptop.jpg",
        },
        {
          id: "patent",
          word: "patent",
          ipa: "/ˈpeɪtnt/",
          pos: "n.",
          vi: "bằng sáng chế",
          exampleEn: "Albert Einstein was granted about 50 patents.",
          exampleVi: "Albert Einstein đã được cấp khoảng 50 bằng sáng chế.",
          imageFile: "patent.jpg",
        },
        {
          id: "portable",
          word: "portable",
          ipa: "/ˈpɔːtəbl/",
          pos: "adj.",
          vi: "cầm tay, dễ mang theo",
          exampleEn: "A tablet is portable. You can put it in your school bag.",
          exampleVi: "Máy tính bảng dễ mang theo. Bạn có thể để nó trong cặp.",
          imageFile: "portable.jpg",
        },
        {
          id: "processor",
          word: "processor",
          ipa: "/ˈprəʊsesə/",
          pos: "n.",
          vi: "bộ xử lý (máy tính)",
          exampleEn: "My computer needs a new processor.",
          exampleVi: "Máy tính của tôi cần một bộ xử lý mới.",
          imageFile: "processor.jpg",
        },
        {
          id: "ram-random-access-memory",
          word: "RAM (Random Access Memory)",
          ipa: "/ræm/ (/ˌrændəm ˌækses ˈmeməri/)",
          pos: "n.",
          vi: "bộ nhớ khả biến (máy tính)",
          exampleEn: "Do you know how to choose RAM for a gaming computer?",
          exampleVi: "Bạn có biết cách chọn RAM cho máy tính chơi game không?",
          imageFile: "ram-random-access-memory.jpg",
        },
        {
          id: "runaway",
          word: "runaway",
          ipa: "/ˈrʌnəweɪ/",
          pos: "adj.",
          vi: "tự di chuyển, không kiểm soát được",
          exampleEn: "Clocky is the name of a runaway alarm clock.",
          exampleVi: "Clocky là tên của một loại đồng hồ báo thức tự ý di chuyển.",
          imageFile: "runaway.jpg",
        },
        {
          id: "smartphone",
          word: "smartphone",
          ipa: "/ˈsmɑːtfəʊn/",
          pos: "n.",
          vi: "điện thoại thông minh",
          exampleEn: "You can watch films on smartphones.",
          exampleVi: "Bạn có thể xem phim trên điện thoại thông minh.",
          imageFile: "smartphone.jpg",
        },
        {
          id: "social-networking-site",
          word: "social networking site",
          ipa: "/ˈsəʊʃl ˈnetwɜːkɪŋ saɪt/",
          pos: "n. phr.",
          vi: "mạng xã hội",
          exampleEn: "Facebook is a popular social networking site.",
          exampleVi: "Facebook là một trang mạng xã hội nổi tiếng.",
          imageFile: "social-networking-site.jpg",
        },
        {
          id: "software",
          word: "software",
          ipa: "/ˈsɒftweə/",
          pos: "n.",
          vi: "phần mềm (máy tính)",
          exampleEn: "You should install this software.",
          exampleVi: "Bạn nên cài đặt phần mềm này.",
          imageFile: "software.jpg",
        },
        {
          id: "solar-charger",
          word: "solar charger",
          ipa: "/ˈsəʊlə ˈtʃɑːdʒə/",
          pos: "n. phr.",
          vi: "sạc năng lượng mặt trời",
          exampleEn: "Using a solar charger is economical.",
          exampleVi: "Sử dụng sạc năng lượng mặt trời rất tiết kiệm.",
          imageFile: "solar-charger.jpg",
        },
        {
          id: "speakers",
          word: "speakers",
          ipa: "/ˈspiːkəz/",
          pos: "n.",
          vi: "loa",
          exampleEn: "Sounds become clearer if you use these speakers.",
          exampleVi: "Âm thanh trở nên rõ hơn nếu bạn dùng bộ loa này.",
          imageFile: "speakers.jpg",
        },
        {
          id: "stain",
          word: "stain",
          ipa: "/steɪn/",
          pos: "n.",
          vi: "vết bẩn",
          exampleEn: "Wipe the dirty stain on your smartphone away.",
          exampleVi: "Hãy lau sạch vết bẩn trên điện thoại thông minh của bạn đi.",
          imageFile: "stain.jpg",
        },
        {
          id: "storage-space",
          word: "storage space",
          ipa: "/ˈstɔːrɪdʒ speɪs/",
          pos: "n.",
          vi: "dung lượng lưu trữ (máy tính)",
          exampleEn: "There's a lot of storage space in my computer.",
          exampleVi: "Có rất nhiều dung lượng lưu trữ trong máy tính của tôi.",
          imageFile: "storage-space.jpg",
        },
        {
          id: "store",
          word: "store",
          ipa: "/stɔː/",
          pos: "v.",
          vi: "lưu trữ",
          exampleEn: "His laptop stores a lot of videos and photos of his students.",
          exampleVi: "Máy tính xách tay của anh ấy lưu trữ rất nhiều video và ảnh của học sinh của anh ấy.",
          imageFile: "store.jpg",
        },
        {
          id: "submarine",
          word: "submarine",
          ipa: "/ˌsʌbməˈriːn/",
          pos: "n.",
          vi: "tàu ngầm",
          exampleEn: "A submarine can travel underwater.",
          exampleVi: "Tàu ngầm có thể di chuyển dưới nước.",
          imageFile: "submarine.jpg",
        },
        {
          id: "suitable",
          word: "suitable",
          ipa: "/ˈsuːtəbl/",
          pos: "adj.",
          vi: "phù hợp",
          exampleEn: "I think this book is suitable for my children.",
          exampleVi: "Tôi nghĩ cuốn sách này phù hợp với con tôi.",
          imageFile: "suitable.jpg",
        },
        {
          id: "valuable",
          word: "valuable",
          ipa: "/ˈvæljuəbl/",
          pos: "adj.",
          vi: "có giá trị",
          exampleEn: "The data will be extremely valuable for medical research.",
          exampleVi: "Dữ liệu này sẽ vô cùng quý giá đối với nghiên cứu y học.",
          imageFile: "valuable.jpg",
        },
        {
          id: "vacuum-cleaner",
          word: "vacuum cleaner",
          ipa: "/ˈvækjuəm ˈkliːnə/",
          pos: "n.",
          vi: "máy hút bụi",
          exampleEn: "A vacuum cleaner can be quite bulky.",
          exampleVi: "Máy hút bụi có thể khá cồng kềnh.",
          imageFile: "vacuum-cleaner.jpg",
        },
        {
          id: "versatile",
          word: "versatile",
          ipa: "/ˈvɜːsətaɪl/",
          pos: "adj.",
          vi: "đa năng, nhiều công dụng",
          exampleEn: "This food processor is versatile. You can mix or chop up wet and dry foods.",
          exampleVi: "Máy xay đa năng này rất đa năng. Bạn có thể trộn hoặc nghiền cả đồ ướt và đồ khô.",
          imageFile: "versatile.jpg",
        },
      ],
    },
  ],
};

export default data;
