import type { UnitVocab } from "../english10.vocab";

/**
 * Unit 4 vocabulary
 */

const data: UnitVocab = {
  unitId: 4,
  unitTitle: "Unit 4: For a Better Community",
  lessons: [
    {
      key: "vocabulary-1",
      title: "Từ vựng Unit 4 – Phần 1",
      baseImagePath: "/images/vocab/u4/",
      items: [
        { id: "access", word: "access", ipa: "/ˈækses/", pos: "n.", vi: "tiếp cận với", exampleEn: "Students must have access to good resources.", exampleVi: "Học sinh phải được tiếp cận với các nguồn tài liệu tốt.", imageFile: "access.jpg" },
        { id: "announcement", word: "announcement", ipa: "/əˈnaʊnsmənt/", pos: "n.", vi: "thông báo", exampleEn: "We saw that announcement on an internet site.", exampleVi: "Chúng tôi đã thấy thông báo đó trên một trang web.", imageFile: "announcement.jpg" },
        { id: "boost", word: "boost", ipa: "/buːst/", pos: "v.", vi: "thúc đẩy, tăng cường", exampleEn: "Exercising every morning helps us boost energy.", exampleVi: "Tập thể dục mỗi sáng giúp chúng ta tăng cường năng lượng.", imageFile: "boost.jpg" },
        { id: "cheerful", word: "cheerful", ipa: "/ˈtʃɪəfl/", pos: "adj.", vi: "vui vẻ", exampleEn: "He's always been a cheerful, hard‑working employee.", exampleVi: "Anh ấy luôn là một nhân viên vui vẻ và chăm chỉ.", imageFile: "cheerful.jpg" },
        { id: "annoying", word: "annoying", ipa: "/əˈnɔɪɪŋ/", pos: "adj.", vi: "gây khó chịu", exampleEn: "John is sometimes annoying.", exampleVi: "John đôi khi gây khó chịu.", imageFile: "annoying.jpg" },
        { id: "annoyed", word: "annoyed", ipa: "/əˈnɔɪd/", pos: "adj.", vi: "khó chịu", exampleEn: "I am annoyed by the big noise.", exampleVi: "Tớ khó chịu với tiếng ồn lớn.", imageFile: "annoyed.jpg" },
        { id: "boring", word: "boring", ipa: "/ˈbɔːrɪŋ/", pos: "adj.", vi: "nhàm chán", exampleEn: "Playing mobile games is boring.", exampleVi: "Chơi trò chơi điện tử thật nhàm chán.", imageFile: "boring.jpg" },
        { id: "bored", word: "bored", ipa: "/bɔːd/", pos: "adj.", vi: "cảm thấy chán", exampleEn: "Brian is bored with Chinese.", exampleVi: "Brian chán học tiếng Trung.", imageFile: "bored.jpg" },
        { id: "dedicated", word: "dedicated", ipa: "/ˈdedɪkeɪtɪd/", pos: "adj.", vi: "tận tụy", exampleEn: "She is the most dedicated doctor.", exampleVi: "Cô ấy là bác sĩ tận tụy nhất.", imageFile: "dedicated.jpg" },
        { id: "hopeless", word: "hopeless", ipa: "/ˈhəʊpləs/", pos: "adj.", vi: "vô vọng, rất kém", exampleEn: "Susan is hopeless at Maths.", exampleVi: "Susan học rất kém môn Toán.", imageFile: "hopeless.jpg" },
        { id: "hopeful", word: "hopeful", ipa: "/ˈhəʊpfl/", pos: "adj.", vi: "lạc quan", exampleEn: "She is hopeful about the future.", exampleVi: "Cô ấy lạc quan về tương lai.", imageFile: "hopeful.jpg" },
        { id: "helpless", word: "helpless", ipa: "/ˈhelpləs/", pos: "adj.", vi: "bất lực", exampleEn: "They are helpless victims of war.", exampleVi: "Họ là nạn nhân bất lực của chiến tranh.", imageFile: "helpless.jpg" },
        { id: "helpful", word: "helpful", ipa: "/ˈhelpfl/", pos: "adj.", vi: "hữu ích", exampleEn: "The host family was very helpful.", exampleVi: "Gia đình chủ nhà rất nhiệt tình.", imageFile: "helpful.jpg" },
        { id: "meaningless", word: "meaningless", ipa: "/ˈmiːnɪŋləs/", pos: "adj.", vi: "vô nghĩa", exampleEn: "Don't lead a meaningless life.", exampleVi: "Đừng sống cuộc đời vô nghĩa.", imageFile: "meaningless.jpg" },
        { id: "meaningful", word: "meaningful", ipa: "/ˈmiːnɪŋfl/", pos: "adj.", vi: "có ý nghĩa", exampleEn: "This is a meaningful activity.", exampleVi: "Đây là hoạt động ý nghĩa.", imageFile: "meaningful.jpg" },
        { id: "charitable-organisation", word: "charitable organisation", ipa: "/ˈtʃærətəbl ˌɔːɡənaɪˈzeɪʃn/", pos: "n. phr.", vi: "tổ chức từ thiện", exampleEn: "This charitable organisation has helped many people.", exampleVi: "Tổ chức từ thiện này đã giúp nhiều người.", imageFile: "charitable-organisation.jpg" },
        { id: "charity-work", word: "charity work", ipa: "/ˈtʃærəti wɜːk/", pos: "n. phr.", vi: "công việc từ thiện", exampleEn: "Teenagers can learn a lot from charity work.", exampleVi: "Thanh thiếu niên học được nhiều từ công việc từ thiện.", imageFile: "charity-work.jpg" },
        { id: "community", word: "community", ipa: "/kəˈmjuːnəti/", pos: "n.", vi: "cộng đồng", exampleEn: "They want to contribute to the community.", exampleVi: "Họ muốn đóng góp cho cộng đồng.", imageFile: "community.jpg" },
        { id: "community-service", word: "community service", ipa: "/kəˈmjuːnəti ˈsɜːvɪs/", pos: "n. phr.", vi: "công việc vì lợi ích cộng đồng", exampleEn: "More students take part in community service.", exampleVi: "Nhiều sinh viên tham gia công việc cộng đồng.", imageFile: "community-service.jpg" },
        { id: "develop", word: "develop", ipa: "/dɪˈveləp/", pos: "v.", vi: "phát triển", exampleEn: "This job helps you develop skills.", exampleVi: "Công việc này giúp bạn phát triển kỹ năng.", imageFile: "develop.jpg" },
        { id: "development", word: "development", ipa: "/dɪˈveləpmənt/", pos: "n.", vi: "sự phát triển", exampleEn: "These activities promote rural development.", exampleVi: "Các hoạt động thúc đẩy phát triển nông thôn.", imageFile: "development.jpg" },
        { id: "disadvantaged", word: "disadvantaged", ipa: "/ˌdɪsədˈvɑːntɪdʒd/", pos: "adj.", vi: "thiệt thòi", exampleEn: "We visited disadvantaged children.", exampleVi: "Chúng tôi thăm trẻ em có hoàn cảnh khó khăn.", imageFile: "disadvantaged.jpg" },
        { id: "donate", word: "donate", ipa: "/dəʊˈneɪt/", pos: "v.", vi: "quyên góp", exampleEn: "They donate clothes and books.", exampleVi: "Họ quyên góp quần áo và sách vở.", imageFile: "donate.jpg" },
        { id: "donation", word: "donation", ipa: "/dəʊˈneɪʃn/", pos: "n.", vi: "sự quyên góp", exampleEn: "All donations are appreciated.", exampleVi: "Mọi sự quyên góp đều đáng trân trọng.", imageFile: "donation.jpg" },
        { id: "donor", word: "donor", ipa: "/ˈdəʊnə(r)/", pos: "n.", vi: "nhà tài trợ, người ủng hộ", exampleEn: "The charity received £100,000 from an unnamed donor.", exampleVi: "Hội từ thiện đã nhận được khoản ủng hộ 100.000 Bảng từ một người ủng hộ giấu tên.", imageFile: "donor.jpg" },
        { id: "handicapped", word: "handicapped", ipa: "/ˈhændikæpt/", pos: "adj.", vi: "khuyết tật", exampleEn: "We take care of handicapped children.", exampleVi: "Chúng tôi chăm sóc trẻ em khuyết tật.", imageFile: "handicapped.jpg" },
        { id: "homeless-people", word: "homeless people", ipa: "/ˈhəʊmləs ˈpiːpl/", pos: "n. phr.", vi: "người vô gia cư", exampleEn: "There are a lot of homeless people in this city.", exampleVi: "Thành phố này có nhiều người vô gia cư.", imageFile: "homeless-people.jpg" },
        { id: "low-income", word: "low-income", ipa: "/ləʊ ˈɪnkʌm/", pos: "adj.", vi: "thu nhập thấp", exampleEn: "We provide support for low-income families.", exampleVi: "Chúng tôi giúp đỡ những gia đình có thu nhập thấp.", imageFile: "low-income.jpg" },
        { id: "needy", word: "needy", ipa: "/ˈniːdi/", pos: "adj.", vi: "túng thiếu, nghèo", exampleEn: "This fund is to help children of needy families.", exampleVi: "Quỹ này nhằm giúp đỡ những em nhỏ sinh ra trong gia đình nghèo.", imageFile: "needy.jpg" },
        { id: "priority", word: "priority", ipa: "/praɪˈɒrəti/", pos: "n.", vi: "ưu tiên", exampleEn: "Protecting the environment is our top priority.", exampleVi: "Bảo vệ môi trường là ưu tiên hàng đầu của chúng ta.", imageFile: "priority.jpg" },
        { id: "raise-money", word: "raise money", ipa: "/reɪz ˈmʌni/", pos: "v. phr.", vi: "quyên góp tiền", exampleEn: "There are a lot of ways to raise money.", exampleVi: "Có rất nhiều cách để quyên góp tiền.", imageFile: "raise-money.jpg" },
        { id: "volunteer-1", word: "volunteer", ipa: "/ˌvɒlənˈtɪə(r)/", pos: "n.", vi: "tình nguyện viên", exampleEn: "They need volunteers to help children with English.", exampleVi: "Họ cần các tình nguyện viên để giúp trẻ con học tiếng Anh.", imageFile: "volunteer-1.jpg" },
        { id: "volunteer-2", word: "volunteer", ipa: "/ˌvɒlənˈtɪə(r)/", pos: "v.", vi: "tình nguyện", exampleEn: "A group of students volunteer to clean this area every Saturday.", exampleVi: "Một nhóm học sinh tình nguyện dọn dẹp khu vực này vào thứ Bảy hàng tuần.", imageFile: "volunteer-2.jpg" },
        { id: "volunteer-work", word: "volunteer work", ipa: "/ˌvɒlənˈtɪə wɜːk/", pos: "n. phr.", vi: "công việc tình nguyện", exampleEn: "She did a lot of volunteer work last summer.", exampleVi: "Cô ấy làm nhiều việc tình nguyện vào mùa hè vừa rồi.", imageFile: "volunteer-work.jpg" },
      ],
    },
    {
      key: "vocabulary-2",
      title: "Từ vựng Unit 4 – Phần 2",
      baseImagePath: "/images/vocab/u4/",
      items: [
        { id: "advertisement", word: "advertisement", ipa: "/ədˈvɜːtɪsmənt/", pos: "n.", vi: "quảng cáo", exampleEn: "I saw your advertisement in the Youth Newspaper yesterday.", exampleVi: "Tôi thấy quảng cáo của các bạn trên tờ Thanh Niên hôm qua.", imageFile: "advertisement.jpg" },
        { id: "application", word: "application", ipa: "/ˌæplɪˈkeɪʃn/", pos: "n.", vi: "sự xin việc, ứng tuyển", exampleEn: "Susan is writing a letter of application.", exampleVi: "Susan đang viết thư xin việc.", imageFile: "application.jpg" },
        { id: "benefit", word: "benefit", ipa: "/ˈbenɪfɪt/", pos: "n.", vi: "lợi ích", exampleEn: "Doing volunteer work has a lot of benefits.", exampleVi: "Làm tình nguyện có rất nhiều lợi ích.", imageFile: "benefit.jpg" },
        { id: "concerned", word: "concerned", ipa: "/kənˈsɜːnd/", pos: "adj.", vi: "quan tâm, lo lắng", exampleEn: "Many young people are concerned about community problems.", exampleVi: "Nhiều người trẻ quan tâm đến các vấn đề cộng đồng.", imageFile: "concerned.jpg" },
        { id: "confidence", word: "confidence", ipa: "/ˈkɒnfɪdəns/", pos: "n.", vi: "sự tự tin", exampleEn: "The course will help you build your confidence.", exampleVi: "Khóa học sẽ giúp bạn xây dựng sự tự tin.", imageFile: "confidence.jpg" },
        { id: "confused", word: "confused", ipa: "/kənˈfjuːzd/", pos: "adj.", vi: "bối rối", exampleEn: "I'm getting really confused. What should I do now?", exampleVi: "Tôi thực sự bối rối. Tôi nên làm gì bây giờ?", imageFile: "confused.jpg" },
        { id: "generous", word: "generous", ipa: "/ˈdʒenərəs/", pos: "adj.", vi: "hào phóng", exampleEn: "Luke is very generous to his friends.", exampleVi: "Luke rất hào phóng với bạn bè.", imageFile: "generous.jpg" },
        { id: "deliver", word: "deliver", ipa: "/dɪˈlɪvə/", pos: "v.", vi: "phân phát, giao hàng", exampleEn: "She’s delivering free drinks to poor people.", exampleVi: "Cô ấy đang phát đồ uống miễn phí cho người nghèo.", imageFile: "deliver.jpg" },
        { id: "involved", word: "involved", ipa: "/ɪnˈvɒlvd/", pos: "adj.", vi: "tham gia, liên quan", exampleEn: "My dad gets involved in many activities to protect the environment.", exampleVi: "Bố tôi tham gia nhiều hoạt động bảo vệ môi trường.", imageFile: "involved.jpg" },
        { id: "life-saving", word: "life-saving", ipa: "/ˈlaɪf seɪvɪŋ/", pos: "adj.", vi: "cứu nạn, cứu sống", exampleEn: "We have learned to use some life-saving appliances.", exampleVi: "Chúng tớ đã học cách dùng một số thiết bị cứu sinh.", imageFile: "life-saving.jpg" },
        { id: "direct-the-traffic", word: "direct the traffic", ipa: "/daɪˈrekt ðə ˈtræfɪk/", pos: "v.", vi: "hướng dẫn giao thông", exampleEn: "Some volunteer students direct the traffic during rush hours.", exampleVi: "Một số sinh viên tình nguyện hướng dẫn giao thông trong giờ cao điểm.", imageFile: "direct-the-traffic.jpg" },
        { id: "experience", word: "experience", ipa: "/ɪkˈspɪəriəns/", pos: "n.", vi: "kinh nghiệm", exampleEn: "Do you have any experience in teaching children?", exampleVi: "Bạn có kinh nghiệm dạy trẻ không?", imageFile: "experience.jpg" },
        { id: "facility", word: "facility", ipa: "/fəˈsɪləti/", pos: "n.", vi: "cơ sở vật chất", exampleEn: "Schools and hospitals are necessary facilities.", exampleVi: "Trường học và bệnh viện là những cơ sở vật chất cần thiết.", imageFile: "facility.jpg" },
        { id: "interact", word: "interact", ipa: "/ˌɪntərˈækt/", pos: "v.", vi: "tương tác", exampleEn: "Volunteers can interact closely with local people.", exampleVi: "Tình nguyện viên có cơ hội tiếp xúc gần với người dân địa phương.", imageFile: "interact.jpg" },
        { id: "narrow-minded", word: "narrow-minded", ipa: "/ˈnærəʊ ˈmaɪndɪd/", pos: "adj.", vi: "hẹp hòi", exampleEn: "He had been narrow-minded before the trip.", exampleVi: "Cậu ấy từng hẹp hòi trước chuyến đi tình nguyện.", imageFile: "narrow-minded.jpg" },
        { id: "non-profit", word: "non-profit", ipa: "/nɒn ˈprɒfɪt/", pos: "adj.", vi: "phi lợi nhuận", exampleEn: "We are a non-profit charity organisation.", exampleVi: "Chúng tôi là tổ chức từ thiện phi lợi nhuận.", imageFile: "non-profit.jpg" },
        { id: "non-governmental", word: "non-governmental", ipa: "/ˌnɒn ˌɡʌvnˈmentl/", pos: "adj.", vi: "phi chính phủ", exampleEn: "They work in a non-governmental organisation.", exampleVi: "Họ làm việc trong một tổ chức phi chính phủ.", imageFile: "non-governmental.jpg" },
        { id: "orphanage", word: "orphanage", ipa: "/ˈɔːfənɪdʒ/", pos: "n.", vi: "trại trẻ mồ côi", exampleEn: "They were brought up in an orphanage.", exampleVi: "Họ được nuôi dưỡng trong một trại trẻ mồ côi.", imageFile: "orphanage.jpg" },
        { id: "practical", word: "practical", ipa: "/ˈpræktɪkl/", pos: "adj.", vi: "thực tế, thiết thực", exampleEn: "I gained a lot of practical experience at the company.", exampleVi: "Tôi đã tích lũy nhiều kinh nghiệm thực tế khi làm việc cho công ty.", imageFile: "practical.jpg" },
        { id: "passionate", word: "passionate", ipa: "/ˈpæʃənət/", pos: "adj.", vi: "đam mê, nồng nhiệt", exampleEn: "I am a passionate and creative person.", exampleVi: "Tôi là một người giàu đam mê và sáng tạo.", imageFile: "passionate.jpg" },
        { id: "position", word: "position", ipa: "/pəˈzɪʃn/", pos: "n.", vi: "vị trí", exampleEn: "I'm applying for the position of a volunteer guide.", exampleVi: "Tôi ứng tuyển vị trí hướng dẫn viên tình nguyện.", imageFile: "position.jpg" },
        { id: "reference", word: "reference", ipa: "/ˈrefrəns/", pos: "n.", vi: "thư giới thiệu", exampleEn: "I can send two references from my teachers.", exampleVi: "Tôi có thể gửi hai thư giới thiệu từ thầy cô.", imageFile: "reference.jpg" },
        { id: "remote-area", word: "remote area", ipa: "/rɪˈməʊt  ˈeəriə/", pos: "n. phr.", vi: "vùng sâu vùng xa", exampleEn: "Our program helps poor households in this remote area.", exampleVi: "Chương trình giúp đỡ các hộ nghèo ở vùng sâu vùng xa.", imageFile: "remote-area.jpg" },
        { id: "running-water", word: "running water", ipa: "/ˈrʌnɪŋ ˈwɔːtə(r)/", pos: "n. phr.", vi: "nước máy", exampleEn: "Residents will be provided with clean running water.", exampleVi: "Cư dân sẽ được cấp nước máy sạch.", imageFile: "running-water.jpg" },
        { id: "rural-area", word: "rural area", ipa: "/ˈrʊərəl ˈeəriə/", pos: "n. phr.", vi: "vùng nông thôn", exampleEn: "Training for jobs should be a priority in rural areas.", exampleVi: "Đào tạo việc làm nên là ưu tiên ở nông thôn.", imageFile: "rural-area.jpg" },
      ],
    },
  ],
};

export default data;
