import type { UnitVocab } from "../english10.vocab";

/**
 * Unit 2 vocabulary
 */

const data: UnitVocab = {
  unitId: 2,
  unitTitle: "Unit 2: Environment and Sustainability",
  lessons: [
    {
      key: "vocabulary-1",
      title: "Từ vựng Unit 2",
      baseImagePath: "/images/vocab/u2/",
      items: [
        {
          id: "adopt",
          word: "adopt",
          ipa: "/əˈdɒpt/",
          pos: "v.",
          vi: "theo, chọn theo",
          exampleEn: "I think we should adopt a greener lifestyle.",
          exampleVi: "Mình nghĩ chúng mình nên sống theo lối sống xanh hơn.",
          imageFile: "adopt.jpg",
        },
        {
          id: "appliance",
          word: "appliance",
          ipa: "/əˈplaɪəns/",
          pos: "n.",
          vi: "thiết bị, đồ dùng, vật dụng",
          exampleEn: "What appliances are there in your house?",
          exampleVi: "Nhà bạn có những vật dụng gì vậy?",
          imageFile: "appliance.jpg",
        },
        {
          id: "atmosphere",
          word: "atmosphere",
          ipa: "/'ætməsfɪə(r)/",
          pos: "n.",
          vi: "khí quyển",
          exampleEn: "The atmosphere is an important part of what makes Earth livable.",
          exampleVi: "Khí quyển là một phần quan trọng khiến cho trái đất có thể sinh sống được.",
          imageFile: "atmosphere.jpg",
        },
        {
          id: "awareness",
          word: "awareness",
          ipa: "/əˈweənəs/",
          pos: "n.",
          vi: "sự nhận thức, hiểu biết, quan tâm",
          exampleEn: "Awareness of climate change has increased in recent decades.",
          exampleVi: "Sự quan tâm đến biến đổi khí hậu đã tăng lên trong vài thập kỷ gần đây.",
          imageFile: "awareness.jpg",
        },
        {
          id: "carbon-footprint",
          word: "carbon footprint",
          ipa: "/ˌkɑːbən 'fʊtprɪnt/",
          pos: "n.",
          vi: "lượng khí CO2 thải ra mỗi ngày",
          exampleEn: "We can change habits to reduce our carbon footprints.",
          exampleVi: "Chúng ta có thể thay đổi thói quen để giảm lượng CO2 thải ra.",
          imageFile: "carbon-footprint.jpg",
        },
        {
          id: "chemical",
          word: "chemical",
          ipa: "/ˈkemɪkl/",
          pos: "n.",
          vi: "chất hóa học",
          exampleEn: "Farmers should reduce their use of chemicals.",
          exampleVi: "Nông dân nên cắt giảm việc sử dụng hoá chất.",
          imageFile: "chemical.jpg",
        },
        {
          id: "clean-up",
          word: "clean-up",
          ipa: "/ˈkliːn ʌp/",
          pos: "n.",
          vi: "sự dọn dẹp, tổng vệ sinh",
          exampleEn: "There have been many clean-up campaigns.",
          exampleVi: "Có nhiều chiến dịch tổng vệ sinh.",
          imageFile: "clean-up.jpg",
        },
        {
          id: "cut-down-on",
          word: "cut down on",
          ipa: "/kʌt daʊn ɒn/",
          pos: "v. phr.",
          vi: "giảm bớt",
          exampleEn: "He's trying to cut down on fatty foods.",
          exampleVi: "Anh ấy đang cố giảm bớt đồ ăn béo.",
          imageFile: "cut-down-on.jpg",
        },
        {
          id: "encourage",
          word: "encourage",
          ipa: "/ɪnˈkʌrɪdʒ/",
          pos: "v.",
          vi: "khuyến khích",
          exampleEn: "We are encouraged to protect the environment.",
          exampleVi: "Chúng mình được khuyến khích bảo vệ môi trường.",
          imageFile: "encourage.jpg",
        },
        {
          id: "estimate",
          word: "estimate",
          ipa: "/ˈestɪmeɪt/",
          pos: "v.",
          vi: "ước tính",
          exampleEn: "It's difficult to estimate how many trees were destroyed.",
          exampleVi: "Rất khó ước tính số cây bị phá huỷ.",
          imageFile: "estimate.jpg",
        },
        {
          id: "eco-friendly",
          word: "eco-friendly",
          ipa: "/ˌiːkəʊ ˈfrendli/",
          pos: "adj.",
          vi: "thân thiện với môi trường",
          exampleEn: "Cycling is an eco-friendly way to travel.",
          exampleVi: "Đi xe đạp là một hình thức di chuyển thân thiện với môi trường.",
          imageFile: "eco-friendly.jpg",
        },
        {
          id: "emission",
          word: "emission",
          ipa: "/i'mɪʃn/",
          pos: "n.",
          vi: "khí thải",
          exampleEn: "We need an action plan to reduce vehicle emissions.",
          exampleVi: "Chúng tôi cần kế hoạch giảm khí thải phương tiện.",
          imageFile: "emission.jpg",
        },
        {
          id: "energy",
          word: "energy",
          ipa: "/ˈenədʒi/",
          pos: "n.",
          vi: "năng lượng",
          exampleEn: "He will give a talk about saving energy.",
          exampleVi: "Ông ấy sẽ nói chuyện về tiết kiệm năng lượng.",
          imageFile: "energy.jpg",
        },
        {
          id: "global",
          word: "global",
          ipa: "/ˈɡləʊbl/",
          pos: "adj.",
          vi: "toàn cầu",
          exampleEn: "Air pollution is a global problem.",
          exampleVi: "Ô nhiễm không khí là vấn đề toàn cầu.",
          imageFile: "global.jpg",
        },
        {
          id: "greenhouse-gas",
          word: "greenhouse gas",
          ipa: "/'griːnhaʊs gæs/",
          pos: "n.",
          vi: "chất khí gây hiệu ứng nhà kính",
          exampleEn: "Factories release greenhouse gases.",
          exampleVi: "Nhà máy thải ra các khí gây hiệu ứng nhà kính.",
          imageFile: "greenhouse-gas.jpg",
        },
        {
          id: "issue",
          word: "issue",
          ipa: "/ˈɪʃuː/",
          pos: "n.",
          vi: "vấn đề",
          exampleEn: "Global warming is a major issue.",
          exampleVi: "Nóng lên toàn cầu là một vấn đề lớn.",
          imageFile: "issue.jpg",
        },
        {
          id: "lifestyle",
          word: "lifestyle",
          ipa: "/ˈlaɪfstaɪl/",
          pos: "n.",
          vi: "lối sống",
          exampleEn: "I'm trying to live a healthy lifestyle.",
          exampleVi: "Mình đang cố sống lành mạnh.",
          imageFile: "lifestyle.jpg",
        },
        {
          id: "litter",
          word: "litter",
          ipa: "/ˈlɪtə/",
          pos: "n.",
          vi: "rác",
          exampleEn: "Please do not leave litter on the street.",
          exampleVi: "Đừng vứt rác ngoài đường.",
          imageFile: "litter.jpg",
        },
        {
          id: "material",
          word: "material",
          ipa: "/məˈtɪəriəl/",
          pos: "n.",
          vi: "nguyên liệu, vật liệu",
          exampleEn: "This bag is made of natural materials.",
          exampleVi: "Chiếc túi này được làm từ những vật liệu thiên nhiên.",
          imageFile: "material.jpg",
        },
        {
          id: "organic",
          word: "organic",
          ipa: "/ɔːˈɡænɪk/",
          pos: "adj.",
          vi: "hữu cơ",
          exampleEn: "Organic food is a little expensive.",
          exampleVi: "Thức ăn hữu cơ hơi đắt.",
          imageFile: "organic.jpg",
        },
        {
          id: "polluted",
          word: "polluted",
          ipa: "/pəˈluːtɪd/",
          pos: "adj.",
          vi: "ô nhiễm",
          exampleEn: "Many rivers have been so polluted that they can no longer be used for drinking water.",
          exampleVi: "Rất nhiều con sông đã bị ô nhiễm và không còn được sử dụng làm nước uống.",
          imageFile: "polluted.jpg",
        },
        {
          id: "public-transport",
          word: "public transport",
          ipa: "/ˌpʌblɪk ˈtrænspɔːt/",
          pos: "n.",
          vi: "phương tiện giao thông công cộng",
          exampleEn: "Using public transport is a good way to protect the environment.",
          exampleVi: "Sử dụng phương tiện giao thông công cộng là một cách hay để bảo vệ môi trường.",
          imageFile: "public-transport.jpg",
        },
        {
          id: "resource",
          word: "resource",
          ipa: "/rɪˈsɔːs/",
          pos: "n.",
          vi: "tài nguyên, nguồn lực",
          exampleEn: "We need to use our natural resources better.",
          exampleVi: "Chúng ta cần sử dụng tài nguyên thiên nhiên tốt hơn.",
          imageFile: "resource.jpg",
        },
        {
          id: "refillable",
          word: "refillable",
          ipa: "/ˌriːˈfɪləbl/",
          pos: "adj.",
          vi: "có thể bơm hoặc làm đầy lại",
          exampleEn: "We should use refillable pens or pencils.",
          exampleVi: "Chúng ta nên sử dụng bút có thể bơm mực hoặc bút chì.",
          imageFile: "refillable.jpg",
        },
        {
          id: "reusable",
          word: "reusable",
          ipa: "/ˌriːˈjuːzəbl/",
          pos: "adj.",
          vi: "có thể tái sử dụng",
          exampleEn: "Use reusable water bottles instead of plastic bottles.",
          exampleVi: "Hãy sử dụng chai nước có thể tái sử dụng thay vì chai nhựa.",
          imageFile: "reusable.jpg",
        },
        {
          id: "set-up",
          word: "set up",
          ipa: "/set ʌp/",
          pos: "v. phr.",
          vi: "thành lập, thiết lập",
          exampleEn: "This club was set up 2 years ago.",
          exampleVi: "Câu lạc bộ này được thành lập cách đây 2 năm.",
          imageFile: "set-up.jpg",
        },
        {
          id: "sustainable",
          word: "sustainable",
          ipa: "/səˈsteɪnəbl/",
          pos: "adj.",
          vi: "bền vững, không gây hại cho môi trường",
          exampleEn: "Economic growth should go hand in hand with environmental protection.",
          exampleVi: "Tăng trưởng kinh tế nên đi cùng với bảo vệ môi trường.",
          imageFile: "sustainable.jpg",
        },
  ],
    },
  ],
};

export default data;            
