import type { UnitVocab } from "../english10.vocab";

/**
 * Unit 3 vocabulary – Music
 */

const data: UnitVocab = {
  unitId: 3,
  unitTitle: "Unit 3: Music",
  lessons: [
    // ✅ PART 1 ---------------------------------------------------------
    {
      key: "vocabulary-1",
      title: "Từ vựng Unit 3 – Phần 1: Chủ đề Âm nhạc",
      baseImagePath: "/images/vocab/u3/",
      items: [
        {
          id: "audience",
          word: "audience",
          ipa: "/ˈɔːdiəns/",
          pos: "n.",
          vi: "khán giả",
          exampleEn: "They want to reach a younger target audience.",
          exampleVi: "Họ muốn tiếp cận đối tượng khán giả trẻ hơn.",
          imageFile: "audience.jpg",
        },
        {
          id: "comment",
          word: "comment",
          ipa: "/ˈkɒment/",
          pos: "n.",
          vi: "lời bình luận",
          exampleEn: "She received many good comments after the show.",
          exampleVi: "Bạn ấy đã nhận được rất nhiều bình luận tốt sau buổi diễn.",
          imageFile: "comment.jpg",
        },
        {
          id: "concert",
          word: "concert",
          ipa: "/ˈkɒnsət/",
          pos: "n.",
          vi: "buổi hòa nhạc",
          exampleEn: "We're organizing a concert for charity.",
          exampleVi: "Chúng tôi đang tổ chức 1 buổi hòa nhạc từ thiện.",
          imageFile: "concert.jpg",
        },
        {
          id: "decoration",
          word: "decoration",
          ipa: "/ˌdekəˈreɪʃn/",
          pos: "n.",
          vi: "việc trang trí",
          exampleEn: "People seemed to like the decoration of this festival.",
          exampleVi: "Mọi người dường như rất thích trang trí của lễ hội này.",
          imageFile: "decoration.jpg",
        },
        {
          id: "delay",
          word: "delay",
          ipa: "/dɪˈleɪ/",
          pos: "v.",
          vi: "hoãn lại",
          exampleEn: "The flight was delayed due to the bad weather.",
          exampleVi: "Chuyến bay đã bị hoãn vì thời tiết xấu.",
          imageFile: "delay.jpg",
        },
        {
          id: "final",
          word: "final",
          ipa: "/ˈfaɪnl/",
          pos: "n.",
          vi: "vòng chung kết",
          exampleEn: "Last week, he got through to the final.",
          exampleVi: "Tuần trước, anh ấy đã lọt vào trận chung kết.",
          imageFile: "final.jpg",
        },
        {
          id: "hesitate",
          word: "hesitate",
          ipa: "/ˈhezɪteɪt/",
          pos: "v.",
          vi: "do dự",
          exampleEn: "She didn’t hesitate before answering the question.",
          exampleVi: "Cô ấy không do dự trước khi trả lời câu hỏi.",
          imageFile: "hesitate.jpg",
        },
        {
          id: "identify-with",
          word: "identify with",
          ipa: "/aɪˈdentɪfaɪ wɪð/",
          pos: "v. phr.",
          vi: "đồng cảm với",
          exampleEn: "They can really identify with her.",
          exampleVi: "Họ thực sự có thể đồng cảm với bà ấy.",
          imageFile: "identify-with.jpg",
        },
        {
          id: "in-search-of",
          word: "in search of",
          ipa: "/ɪn sɜːtʃ əv/",
          pos: "idiom",
          vi: "đi tìm",
          exampleEn: "He goes all around his country in search of the best singers.",
          exampleVi: "Anh ấy đi khắp đất nước để tìm các ca sĩ giỏi nhất.",
          imageFile: "in-search-of.jpg",
        },
        {
          id: "live-adj",
          word: "live",
          ipa: "/laɪv/",
          pos: "adj.",
          vi: "trực tiếp",
          exampleEn: "The music show is live on TV now.",
          exampleVi: "Chương trình ca nhạc đang phát trực tiếp.",
          imageFile: "live-adj.jpg",
        },
        {
          id: "live-adv",
          word: "live",
          ipa: "/laɪv/",
          pos: "adv.",
          vi: "trực tiếp",
          exampleEn: "The music band is performing live on TV.",
          exampleVi: "Ban nhạc đang biểu diễn trực tiếp.",
          imageFile: "live-adv.jpg",
        },
        {
          id: "location",
          word: "location",
          ipa: "/ləʊˈkeɪʃn/",
          pos: "n.",
          vi: "vị trí",
          exampleEn: "Her company is moving to a new location.",
          exampleVi: "Công ty cô ấy sắp chuyển đến địa điểm mới.",
          imageFile: "location.jpg",
        },
        {
          id: "perform",
          word: "perform",
          ipa: "/pəˈfɔːm/",
          pos: "v.",
          vi: "biểu diễn",
          exampleEn: "Many famous artists have performed in the programme.",
          exampleVi: "Nhiều nghệ sĩ nổi tiếng đã biểu diễn.",
          imageFile: "perform.jpg",
        },
        {
          id: "performer",
          word: "performer",
          ipa: "/pəˈfɔːmə(r)/",
          pos: "n.",
          vi: "người biểu diễn",
          exampleEn: "By the age of 13, Allan had become an experienced circus performer.",
          exampleVi: "Ở tuổi 13, Allan đã là nghệ sĩ xiếc giàu kinh nghiệm.",
          imageFile: "performer.jpg",
        },
        {
          id: "performance",
          word: "performance",
          ipa: "/pəˈfɔːməns/",
          pos: "n.",
          vi: "màn biểu diễn",
          exampleEn: "Facial expression is important in a dance performance.",
          exampleVi: "Biểu cảm khuôn mặt rất quan trọng trong biểu diễn khiêu vũ.",
          imageFile: "performance.jpg",
        },
        {
          id: "reality-tv",
          word: "reality TV show",
          ipa: "/riˈæləti ˌtiː ˈviː ʃəʊ/",
          pos: "n. phr.",
          vi: "chương trình truyền hình thực tế",
          exampleEn: "Reality TV shows are not very interesting to many people.",
          exampleVi: "Nhiều người thấy chương trình truyền hình thực tế không thú vị.",
          imageFile: "reality-tv.jpg",
        },
        {
          id: "renowned",
          word: "renowned",
          ipa: "/rɪˈnaʊnd/",
          pos: "adj.",
          vi: "nổi tiếng",
          exampleEn: "He is a renowned actor.",
          exampleVi: "Ông ấy là một diễn viên nổi tiếng.",
          imageFile: "renowned.jpg",
        },
        {
          id: "runner-up",
          word: "runner-up",
          ipa: "/ˌrʌnər ˈʌp/",
          pos: "n.",
          vi: "á quân",
          exampleEn: "She is one of the two runners-up in the competition.",
          exampleVi: "Cô ấy là một trong hai Á quân của cuộc thi.",
          imageFile: "runner-up.jpg",
        },
        {
          id: "semi-final",
          word: "semi-final",
          ipa: "/ˌsemi ˈfaɪnl/",
          pos: "n.",
          vi: "vòng bán kết",
          exampleEn: "They’ve just been through to the semi-final.",
          exampleVi: "Họ vừa lọt vào vòng bán kết.",
          imageFile: "semi-final.jpg",
        },
      ],
    },

    // ✅ PART 2 ---------------------------------------------------------
    {
      key: "vocabulary-2",
      title: "Từ vựng Unit 3 – Phần 2: Chủ đề Âm nhạc (tiếp theo)",
      baseImagePath: "/images/vocab/u3/",
      items: [
        {
          id: "achievement",
          word: "achievement",
          ipa: "/əˈtʃiːvmənt/",
          pos: "n.",
          vi: "thành tựu",
          exampleEn: "It was a great achievement for such a young singer.",
          exampleVi: "Đó là thành tựu lớn với một ca sĩ trẻ.",
          imageFile: "achievement.jpg",
        },
        {
          id: "bamboo-clappers",
          word: "bamboo clappers",
          ipa: "/ˌbæmˈbuː ˈklæpəz/",
          pos: "n.",
          vi: "phách",
          exampleEn: "Bamboo clappers are the main musical instruments in Chau Van performance.",
          exampleVi: "Phách là nhạc cụ chính trong hát Chầu Văn.",
          imageFile: "bamboo-clappers.jpg",
        },
        {
          id: "biography",
          word: "biography",
          ipa: "/baɪˈɒɡrəfi/",
          pos: "n.",
          vi: "tiểu sử",
          exampleEn: "The singer's biography can be easily found online.",
          exampleVi: "Tiểu sử của ca sĩ có thể dễ dàng tìm trên mạng.",
          imageFile: "biography.jpg",
        },
        {
          id: "competition",
          word: "competition",
          ipa: "/ˌkɒmpəˈtɪʃn/",
          pos: "n.",
          vi: "cuộc thi",
          exampleEn: "Who do you think will win that cooking competition?",
          exampleVi: "Bạn nghĩ ai sẽ thắng cuộc thi nấu ăn itu?",
          imageFile: "competition.jpg",
        },
        {
          id: "competitive",
          word: "competitive",
          ipa: "/kəmˈpetətɪv/",
          pos: "adj.",
          vi: "mang tính cạnh tranh",
          exampleEn: "The entertainment industry is getting more competitive.",
          exampleVi: "Ngành giải trí ngày càng cạnh tranh.",
          imageFile: "competitive.jpg",
        },
        {
          id: "compose",
          word: "compose",
          ipa: "/kəmˈpəʊz/",
          pos: "v.",
          vi: "sáng tác",
          exampleEn: "This song was specially composed for the contest winner.",
          exampleVi: "Bài hát này được sáng tác riêng cho người thắng cuộc thi.",
          imageFile: "compose.jpg",
        },
        {
          id: "composer",
          word: "composer",
          ipa: "/kəmˈpəʊzə(r)/",
          pos: "n.",
          vi: "nhà soạn nhạc",
          exampleEn: "He has been very successful as a composer.",
          exampleVi: "Ông ấy là nhà soạn nhạc rất thành công.",
          imageFile: "composer.jpg",
        },
        {
          id: "contest",
          word: "contest",
          ipa: "/ˈkɒntest/",
          pos: "n.",
          vi: "cuộc thi",
          exampleEn: "He won second place in the singing contest last year.",
          exampleVi: "Anh ấy đạt giải nhì cuộc thi hát năm ngoái.",
          imageFile: "contest.jpg",
        },
        {
          id: "contestant",
          word: "contestant",
          ipa: "/kənˈtestənt/",
          pos: "n.",
          vi: "thí sinh",
          exampleEn: "The contestants are practicing very hard for tonight’s show.",
          exampleVi: "Các thí sinh đang luyện tập chăm chỉ cho buổi diễn tối nay.",
          imageFile: "contestant.jpg",
        },
        {
          id: "eliminate",
          word: "eliminate",
          ipa: "/ɪˈlɪmɪneɪt/",
          pos: "v.",
          vi: "loại",
          exampleEn: "Two contestants were eliminated from last night's show.",
          exampleVi: "Hai thí sinh đã bị loại khỏi buổi diễn hôm qua.",
          imageFile: "eliminate.jpg",
        },
        {
          id: "gong",
          word: "gong",
          ipa: "/ɡɒŋ/",
          pos: "n.",
          vi: "chiêng, cồng",
          exampleEn: "Don’t beat the gong. It's noisy.",
          exampleVi: "Đừng đánh chiêng nữa, ồn lắm.",
          imageFile: "gong.jpg",
        },
        {
          id: "innovation",
          word: "innovation",
          ipa: "/ˌɪnəˈveɪʃn/",
          pos: "n.",
          vi: "sự đổi mới",
          exampleEn: "Great innovations have been made by famous composers.",
          exampleVi: "Những đổi mới lớn đã được tạo ra bởi các nhà soạn nhạc nổi tiếng.",
          imageFile: "innovation.jpg",
        },
        {
          id: "judge",
          word: "judge",
          ipa: "/dʒʌdʒ/",
          pos: "n.",
          vi: "giám khảo",
          exampleEn: "She was invited to be a judge in a singing competition.",
          exampleVi: "Cô ấy được mời làm giám khảo trong cuộc thi hát.",
          imageFile: "judge.jpg",
        },
        {
          id: "launch",
          word: "launch",
          ipa: "/lɔːntʃ/",
          pos: "v.",
          vi: "ra mắt",
          exampleEn: "Do you know where the Idol programme first launched?",
          exampleVi: "Bạn có biết chương trình Thần tượng ra mắt lần đầu ở đâu không?",
          imageFile: "launch.jpg",
        },
        {
          id: "musical-instrument",
          word: "musical instrument",
          ipa: "/ˈmjuːzɪkl ˈɪnstrəmənt/",
          pos: "n. phr.",
          vi: "nhạc cụ",
          exampleEn: "Learning a musical instrument can help boost confidence.",
          exampleVi: "Biết chơi một nhạc cụ có thể giúp tăng sự tự tin.",
          imageFile: "musical-instrument.jpg",
        },
        {
          id: "passionate",
          word: "passionate",
          ipa: "/ˈpæʃənət/",
          pos: "adj.",
          vi: "nồng nhiệt, đam mê",
          exampleEn: "He has had a passionate interest in music since childhood.",
          exampleVi: "Anh ấy đam mê âm nhạc từ nhỏ.",
          imageFile: "passionate.jpg",
        },
        {
          id: "moon-shaped-lute",
          word: "moon-shaped lute",
          ipa: "/muːn ʃeɪpt luːt/",
          pos: "n.",
          vi: "đàn nguyệt",
          exampleEn: "Can she play the moon-shaped lute?",
          exampleVi: "Cô ấy có biết chơi đàn nguyệt không?",
          imageFile: "moon-shaped-lute.jpg",
        },
        {
          id: "participate",
          word: "participate",
          ipa: "/pɑːˈtɪsɪpeɪt/",
          pos: "v.",
          vi: "tham gia",
          exampleEn: "The children participated in many competitions.",
          exampleVi: "Bọn trẻ đã tham gia nhiều cuộc thi.",
          imageFile: "participate.jpg",
        },
        {
          id: "participant",
          word: "participant",
          ipa: "/pɑːˈtɪsɪpənt/",
          pos: "n.",
          vi: "người tham dự",
          exampleEn: "All participants must be under 15 years old.",
          exampleVi: "Tất cả thí sinh phải dưới 15 tuổi.",
          imageFile: "participant.jpg",
        },
        {
          id: "reach",
          word: "reach",
          ipa: "/riːtʃ/",
          pos: "v.",
          vi: "đạt được",
          exampleEn: "The movie has reached more than 3 billion dollars.",
          exampleVi: "Bộ phim đã đạt hơn 3 tỷ đô la.",
          imageFile: "reach.jpg",
        },
        {
          id: "release",
          word: "release",
          ipa: "/rɪˈliːs/",
          pos: "v.",
          vi: "phát hành",
          exampleEn: "She is trying to release her album as planned.",
          exampleVi: "Cô ấy đang cố gắng phát hành album như dự định.",
          imageFile: "release.jpg",
        },
        {
          id: "social-media",
          word: "social media",
          ipa: "/ˌsəʊʃl ˈmiːdiə/",
          pos: "n.",
          vi: "mạng xã hội",
          exampleEn: "Social media are changing the way people communicate.",
          exampleVi: "Mạng xã hội đang thay đổi cách mọi người giao tiếp.",
          imageFile: "social-media.jpg",
        },
        {
          id: "spread",
          word: "spread",
          ipa: "/spred/",
          pos: "v.",
          vi: "lan truyền",
          exampleEn: "The news spreads faster and faster.",
          exampleVi: "Tin tức lan truyền ngày càng nhanh.",
          imageFile: "spread.jpg",
        },
        {
          id: "talented",
          word: "talented",
          ipa: "/ˈtæləntɪd/",
          pos: "adj.",
          vi: "tài năng",
          exampleEn: "The contest aims to find talented singers.",
          exampleVi: "Cuộc thi nhằm tìm ra những ca sĩ tài năng.",
          imageFile: "talented.jpg",
        },
        {
          id: "trumpet",
          word: "trumpet",
          ipa: "/ˈtrʌmpɪt/",
          pos: "n.",
          vi: "kèn trumpet",
          exampleEn: "The man is blowing his trumpet.",
          exampleVi: "Người đàn ông đang thổi kèn trumpet.",
          imageFile: "trumpet.jpg",
        },
        {
          id: "worship",
          word: "worship",
          ipa: "/ˈwɜːʃɪp/",
          pos: "v.",
          vi: "thờ, thờ cúng",
          exampleEn: "The churches were built to worship Gods.",
          exampleVi: "Nhà thờ được xây dựng để thờ phụng Chúa.",
          imageFile: "worship.jpg",
        },
        {
          id: "upload",
          word: "upload",
          ipa: "/ˌʌpˈləʊd/",
          pos: "v.",
          vi: "tải lên",
          exampleEn: "His song videos were uploaded on Sunday.",
          exampleVi: "Các video bài hát của anh ấy đã được tải lên vào Chủ Nhật.",
          imageFile: "upload.jpg",
        },
      ],
    },
  ],
};

export default data;
