// content/practice/vocab/en10.u3.v2.ex2.ts
import type { VocabTriple } from "./en10.u1.v1.ex1";

export const u3V2Ex2Data: VocabTriple[] = [
  {
    id: "achievement",
    en: "achievement",
    vi: "thành tựu",
    typeLabel: "Noun (n.)",
    audioText: "achievement",
  },
  {
    id: "bamboo-clappers",
    en: "bamboo clappers",
    vi: "phách",
    typeLabel: "Noun phrase (n. phr.)",
    audioText: "bamboo clappers",
  },
  {
    id: "biography",
    en: "biography",
    vi: "tiểu sử",
    typeLabel: "Noun (n.)",
    audioText: "biography",
  },
  {
    id: "competition",
    en: "competition",
    vi: "cuộc thi",
    typeLabel: "Noun (n.)",
    audioText: "competition",
  },
  {
    id: "competitive",
    en: "competitive",
    vi: "mang tính cạnh tranh",
    typeLabel: "Adjective (adj.)",
    audioText: "competitive",
  },
  {
    id: "compose",
    en: "compose",
    vi: "sáng tác",
    typeLabel: "Verb (v.)",
    audioText: "compose",
  },
  {
    id: "composer",
    en: "composer",
    vi: "nhà soạn nhạc",
    typeLabel: "Noun (n.)",
    audioText: "composer",
  },
  {
    id: "contest",
    en: "contest",
    vi: "cuộc thi",
    typeLabel: "Noun (n.)",
    audioText: "contest",
  },
  {
    id: "contestant",
    en: "contestant",
    vi: "thí sinh",
    typeLabel: "Noun (n.)",
    audioText: "contestant",
  },
  {
    id: "eliminate",
    en: "eliminate",
    vi: "loại",
    typeLabel: "Verb (v.)",
    audioText: "eliminate",
  },
  {
    id: "gong",
    en: "gong",
    vi: "chiêng, cồng",
    typeLabel: "Noun (n.)",
    audioText: "gong",
  },
  {
    id: "innovation",
    en: "innovation",
    vi: "sự đổi mới",
    typeLabel: "Noun (n.)",
    audioText: "innovation",
  },
  {
    id: "judge",
    en: "judge",
    vi: "giám khảo",
    typeLabel: "Noun (n.)",
    audioText: "judge",
  },
  {
    id: "launch",
    en: "launch",
    vi: "ra mắt",
    typeLabel: "Verb (v.)",
    audioText: "launch",
  },
  {
    id: "musical-instrument",
    en: "musical instrument",
    vi: "nhạc cụ",
    typeLabel: "Noun phrase (n. phr.)",
    audioText: "musical instrument",
  },
  {
    id: "passionate",
    en: "passionate",
    vi: "nồng nhiệt, đam mê",
    typeLabel: "Adjective (adj.)",
    audioText: "passionate",
  },
  {
    id: "moon-shaped-lute",
    en: "moon-shaped lute",
    vi: "đàn nguyệt",
    typeLabel: "Noun phrase (n. phr.)",
    audioText: "moon-shaped lute",
  },
  {
    id: "participate",
    en: "participate",
    vi: "tham gia",
    typeLabel: "Verb (v.)",
    audioText: "participate",
  },
  {
    id: "participant",
    en: "participant",
    vi: "người tham dự",
    typeLabel: "Noun (n.)",
    audioText: "participant",
  },
  {
    id: "reach",
    en: "reach",
    vi: "đạt được",
    typeLabel: "Verb (v.)",
    audioText: "reach",
  },
  {
    id: "release",
    en: "release",
    vi: "phát hành",
    typeLabel: "Verb (v.)",
    audioText: "release",
  },
  {
    id: "social-media",
    en: "social media",
    vi: "mạng xã hội",
    typeLabel: "Noun phrase (n. phr.)",
    audioText: "social media",
  },
  {
    id: "spread",
    en: "spread",
    vi: "lan truyền",
    typeLabel: "Verb (v.)",
    audioText: "spread",
  },
  {
    id: "talented",
    en: "talented",
    vi: "tài năng",
    typeLabel: "Adjective (adj.)",
    audioText: "talented",
  },
  {
    id: "trumpet",
    en: "trumpet",
    vi: "kèn trumpet",
    typeLabel: "Noun (n.)",
    audioText: "trumpet",
  },
  {
    id: "worship",
    en: "worship",
    vi: "thờ, thờ cúng",
    typeLabel: "Verb (v.)",
    audioText: "worship",
  },
  {
    id: "upload",
    en: "upload",
    vi: "tải lên",
    typeLabel: "Verb (v.)",
    audioText: "upload",
  },
];
